services:
  - type: web
    name: estateiq-backend
    env: python
    rootDir: backend
    plan: free

    runtime: python-3.11.9

    buildCommand: pip install --only-binary=:all: -r requirements.txt

    startCommand: gunicorn --bind 0.0.0.0:$PORT server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9